extends:
  - airbnb-base
  - eslint:recommended

env:
  node: true

rules:
  indent:
    - warn
    - 4
    - SwitchCase: 1
  quotes:
    - warn
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-use-before-define:
    - error
    - functions: false
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  require-await:
    - error

parserOptions:
  ecmaVersion: 2018
  sourceType: module
