extends: airbnb-base

env:
  node: true

rules:
  indent:
    - warn
    - 4
    - SwitchCase: 1
  no-console: off
  no-plusplus:
   - error
   - allowForLoopAfterthoughts: true
  no-use-before-define:
    - error
    - functions: false
  object-curly-newline:
    - error
    - consistent: true